import { useEffect, useRef, useState } from 'react';
import { BackHandler, KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { dateRange, emptyTrip, id, members, parties, sampleTrip, settlement, shortDate, won, type Party, type Schedule, type Trip } from './model';
import { Button, Chip, colors as c, Empty, Field, Heading, Icon, IconButton, Label, s, type IconName } from './ui';

type Tab = 'overview' | 'schedule' | 'map' | 'expenses' | 'chat';
type Sheet = 'trips' | 'newTrip' | 'members' | 'notice' | 'schedule' | 'expense' | 'place' | 'checklist' | null;
const tabs: { key: Tab; label: string; icon: IconName }[] = [
  { key: 'overview', label: '요약', icon: 'home' }, { key: 'schedule', label: '일정', icon: 'calendar' },
  { key: 'map', label: '지도', icon: 'map' }, { key: 'expenses', label: '정산', icon: 'wallet' }, { key: 'chat', label: '대화', icon: 'chat' },
];

export default function DemoApp() {
  const [trips, setTrips] = useState<Trip[]>(() => [sampleTrip()]);
  const [tripId, setTripId] = useState('gangneung');
  const [tab, setTab] = useState<Tab>('overview');
  const [sheet, setSheet] = useState<Sheet>(null);
  const [day, setDay] = useState(0);
  const [party, setParty] = useState<Party>('전체');
  const [costView, setCostView] = useState('지출 내역');
  const [search, setSearch] = useState('');
  const [message, setMessage] = useState('');
  const [checkInput, setCheckInput] = useState('');
  const [error, setError] = useState('');
  const [form, setForm] = useState<Record<string, string>>({});
  const [formParty, setFormParty] = useState<Party>('전체');
  const [payer, setPayer] = useState('지우');
  const [participants, setParticipants] = useState([...members]);
  const [editId, setEditId] = useState<string | null>(null);
  const [selectedPlaceId, setSelectedPlaceId] = useState<string | null>(null);
  const scroll = useRef<ScrollView>(null);
  const trip = trips.find(t => t.id === tripId)!;
  const total = trip.expenses.reduce((sum, e) => sum + e.amount, 0);
  const accounting = settlement(trip.expenses);
  const completed = trip.checklist.filter(item => item.done).length;
  const schedules = trip.schedules.filter(item => item.day === day && (party === '전체' || item.party === '전체' || item.party === party)).sort((a, b) => a.time.localeCompare(b.time));
  const foundPlaces = trip.places.filter(p => `${p.name} ${p.category} ${p.address}`.includes(search));
  const selectedPlace = foundPlaces.find(p => p.id === selectedPlaceId) ?? foundPlaces[0];

  const update = (change: (current: Trip) => Trip) => setTrips(current => current.map(t => t.id === tripId ? change(t) : t));
  const go = (next: Tab) => { setTab(next); scroll.current?.scrollTo({ y: 0, animated: false }); };
  const open = (next: Sheet, values: Record<string, string> = {}) => { setError(''); setForm(values); setEditId(null); setFormParty(party); setPayer('지우'); setParticipants([...members]); setSheet(next); };
  const editSchedule = (item: Schedule) => { setDay(item.day); open('schedule', { title: item.title, place: item.place, time: item.time }); setFormParty(item.party); setEditId(item.id); };
  const chooseTrip = (next: Trip) => { setTripId(next.id); setDay(0); setParty('전체'); setSearch(''); setSelectedPlaceId(null); setMessage(''); setCheckInput(''); setCostView('지출 내역'); setSheet(null); go('overview'); };
  const input = (key: string) => ({ value: form[key] ?? '', onChangeText: (value: string) => setForm(current => ({ ...current, [key]: value })) });

  useEffect(() => {
    const handler = BackHandler.addEventListener('hardwareBackPress', () => {
      if (sheet) { setSheet(null); return true; }
      if (tab !== 'overview') { setTab('overview'); return true; }
      return false;
    });
    return () => handler.remove();
  }, [sheet, tab]);

  function save() {
    const title = form.title?.trim();
    if (sheet === 'schedule') {
      if (!title || !/^([01]\d|2[0-3]):[0-5]\d$/.test(form.time ?? '')) { setError('일정 제목과 올바른 시간(HH:MM)을 입력해 주세요.'); return; }
      const item: Schedule = { id: editId ?? id(), title, day, time: form.time, place: form.place?.trim() || '장소 미정', party: formParty };
      update(t => ({ ...t, schedules: editId ? t.schedules.map(x => x.id === editId ? item : x) : [...t.schedules, item] }));
    } else if (sheet === 'expense') {
      const raw = (form.amount ?? '').replaceAll(',', '').trim();
      const amount = Number(raw);
      if (!title || !/^\d+$/.test(raw) || !Number.isSafeInteger(amount) || amount <= 0 || amount > 100000000 || !participants.length) { setError('항목명, 1원~1억원의 정수 금액, 부담할 멤버를 입력해 주세요.'); return; }
      update(t => ({ ...t, expenses: [...t.expenses, { id: id(), title, amount, payer, participants: members.filter(m => participants.includes(m)) }] }));
    } else if (sheet === 'notice') {
      if (!form.notice?.trim()) { setError('공지 내용을 입력해 주세요.'); return; }
      update(t => ({ ...t, notice: form.notice.trim() }));
    } else if (sheet === 'place') {
      if (!title) { setError('장소 이름을 입력해 주세요.'); return; }
      const placeId = id();
      update(t => ({ ...t, places: [...t.places, { id: placeId, name: title, category: form.category?.trim() || '기타', address: form.address?.trim() || '주소 미정', note: form.note?.trim() || '' }] }));
      setSelectedPlaceId(placeId); setSearch('');
    } else if (sheet === 'newTrip') {
      const dates = dateRange(form.start ?? '', form.end ?? '');
      if (!title || !form.region?.trim() || !dates.length) { setError('여행명·지역과 올바른 날짜를 입력해 주세요. 데모는 최대 14일 여행을 지원합니다.'); return; }
      const next = emptyTrip(title, form.region.trim(), dates);
      setTrips(current => [...current, next]); chooseTrip(next); return;
    }
    setSheet(null);
  }
  function toggleCheck(itemId: string) { update(t => ({ ...t, checklist: t.checklist.map(item => item.id === itemId ? { ...item, done: !item.done } : item) })); }
  function addCheck() {
    if (!checkInput.trim()) return;
    update(t => ({ ...t, checklist: [...t.checklist, { id: id(), title: checkInput.trim(), owner: '지우', done: false }] })); setCheckInput('');
  }
  function send() {
    if (!message.trim()) return;
    const now = new Date();
    update(t => ({ ...t, messages: [...t.messages, { id: id(), author: '지우', text: message.trim(), time: `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}` }] }));
    setMessage('');
  }
  function DatePicker() {
    return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={st.dateRow}>{trip.dates.map((date, i) => <Pressable key={date} accessibilityRole="button" accessibilityLabel={`${i + 1}일차 ${shortDate(date)}`} accessibilityState={{ selected: day === i }} onPress={() => setDay(i)} style={[st.date, day === i && st.dateActive]}><Text style={[st.dayLabel, day === i && st.onGreen]}>DAY {i + 1}</Text><Text style={[st.dateLabel, day === i && st.onGreen]}>{shortDate(date)}</Text></Pressable>)}</ScrollView>;
  }
  function PartyPicker() { return <View style={st.wrap}>{parties.map(p => <Chip key={p} label={p} selected={party === p} onPress={() => setParty(p)} />)}</View>; }
  function Timeline({ items }: { items: Schedule[] }) {
    return <View>{items.map((item, i) => <Pressable accessibilityRole="button" accessibilityLabel={`${item.time} ${item.title} 수정`} onPress={() => editSchedule(item)} key={item.id} style={st.timelineRow}><View style={st.timeColumn}><Text style={st.time}>{item.time}</Text><View style={[st.dot, { backgroundColor: item.party === '전체' ? c.green : c.orange }]} />{i < items.length - 1 && <View style={st.stem} />}</View><View style={st.event}><View style={s.between}><Text style={st.eventTitle}>{item.title}</Text><Icon name="arrow" size={16} color={c.muted} /></View><View style={[s.row, { marginTop: 8 }]}><Icon name="pin" size={14} color={c.muted} /><Text style={s.label}>{item.place}</Text></View><Text style={st.tag}>{item.party} · {item.party === '전체' ? '4명' : '2명'}</Text></View></Pressable>)}</View>;
  }
  function Checklist({ compact = false }: { compact?: boolean }) {
    return <View>{(compact ? trip.checklist.slice(0, 3) : trip.checklist).map(item => <Pressable key={item.id} accessibilityRole="checkbox" accessibilityLabel={item.title} accessibilityState={{ checked: item.done }} onPress={() => toggleCheck(item.id)} style={st.checkRow}><View style={[st.checkbox, item.done && { backgroundColor: c.green, borderColor: c.green }]}>{item.done && <Icon name="check" size={14} color={c.white} />}</View><Text style={[st.checkText, item.done && st.checkedText]}>{item.title}</Text><Text style={s.label}>{item.owner}</Text></Pressable>)}</View>;
  }

  return <View style={st.outer}><SafeAreaView style={st.app} edges={['top', 'bottom']}>
    <View style={st.topbar}><Pressable accessibilityRole="button" accessibilityLabel="내 여행 목록" onPress={() => open('trips')} style={s.row}><View style={st.brandMark}><Icon name="map" color={c.white} size={21} /></View><Text style={st.brand}>모여행</Text><Text style={st.demo}>DEMO</Text></Pressable><IconButton name="users" label="멤버와 파티" onPress={() => open('members')} /></View>
    <Pressable accessibilityRole="button" accessibilityLabel="여행 전환" onPress={() => open('trips')} style={st.tripbar}><View style={{ flex: 1 }}><Text style={st.tripName}>{trip.name} <Text style={s.label}>⌄</Text></Text><Text style={s.label}>{shortDate(trip.dates[0])} — {shortDate(trip.dates[trip.dates.length - 1])} · {trip.dates.length}일 · {members.length}명</Text></View><View style={st.avatars}>{members.slice(0, 3).map((m, i) => <View key={m} style={[st.avatar, { backgroundColor: ['#DAE9DB', '#F7DFB8', '#DAE5EF'][i] }]}><Text style={st.avatarText}>{m.slice(0, 1)}</Text></View>)}<Text style={s.label}>+1</Text></View></Pressable>
    <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
    <ScrollView ref={scroll} style={{ flex: 1 }} contentContainerStyle={st.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} onContentSizeChange={() => { if (tab === 'chat') scroll.current?.scrollToEnd({ animated: true }); }}>
      {tab === 'overview' && <>
        <View style={st.hero}><View style={st.sun} /><View style={st.waveBack} /><View style={st.waveFront} /><View style={st.heroCopy}><Text style={st.eyebrow}>A LITTLE TRIP, TOGETHER</Text><Text style={st.heroTitle}>함께라서 더 좋은,{ '\n' }이번 여행.</Text><Text style={st.heroSubtitle}>{trip.region}에서 쌓을 우리의 작은 순간들</Text><Pressable accessibilityRole="button" onPress={() => go('schedule')} style={st.heroButton}><Text style={st.heroButtonText}>여행 일정 보기</Text><Icon name="arrow" size={17} color={c.green} /></Pressable></View><Text style={st.heroStamp}>{trip.region.toUpperCase()} / {trip.dates[0].slice(0, 4)}</Text></View>
        <Pressable accessibilityRole="button" onPress={() => open('notice', { notice: trip.notice })} style={st.notice}><View style={st.noticeIcon}><Icon name="bell" size={18} color={c.green} /></View><View style={{ flex: 1 }}><Text style={st.noticeLabel}>함께 확인해요</Text><Text numberOfLines={1} style={st.noticeText}>{trip.notice}</Text></View><Icon name="arrow" size={17} color={c.muted} /></Pressable>
        <Heading action="전체 보기" onPress={() => go('schedule')}>다가오는 일정</Heading>
        {trip.schedules.length ? <Timeline items={[...trip.schedules].sort((a, b) => a.day - b.day || a.time.localeCompare(b.time)).slice(0, 2)} /> : <Empty title="여행의 첫 순간을 계획해요" detail="일정 탭에서 가보고 싶은 곳을 추가해 보세요." />}
        <Heading action={`${completed}/${trip.checklist.length} 완료`} onPress={() => open('checklist')}>준비도 함께</Heading><View style={s.card}><View style={st.progress}><View style={[st.progressFill, { width: `${trip.checklist.length ? completed / trip.checklist.length * 100 : 0}%` }]} /></View><Checklist compact /><Pressable accessibilityRole="button" onPress={() => open('checklist')} style={st.checkMore}><Text style={s.link}>준비물 모두 보기 +</Text></Pressable></View>
        <Pressable accessibilityRole="button" onPress={() => go('expenses')} style={st.costPreview}><View><Label>지금까지 함께 쓴 비용</Label><Text style={st.costNumber}>{won(total)}</Text></View><Icon name="arrow" color={c.green} /></Pressable>
      </>}
      {tab === 'schedule' && <><View style={s.between}><View><Text style={st.pageTitle}>우리의 여행 일정</Text><Text style={s.body}>따로, 또 같이 보내는 시간</Text></View><IconButton name="plus" label="일정 추가" onPress={() => open('schedule', { time: '10:00' })} /></View><DatePicker /><PartyPicker /><Heading action="지도 보기" onPress={() => go('map')}>{shortDate(trip.dates[day])}의 계획</Heading>{schedules.length ? <Timeline items={schedules} /> : <Empty title="아직 비어 있는 하루예요" detail="첫 일정을 추가해 여행을 채워 보세요." />}<Button label="일정 추가하기" icon="plus" onPress={() => open('schedule', { time: '10:00' })} /><Text style={st.footnote}>일정을 누르면 수정하거나 삭제할 수 있어요.</Text></>}
      {tab === 'map' && <><Text style={st.pageTitle}>가보고 싶은 곳</Text><Text style={s.body}>장소를 모으고, 하루의 동선을 그려요.</Text><View style={{ marginTop: 18 }}><Field label="저장한 장소 검색" value={search} onChangeText={setSearch} placeholder="장소명, 카테고리, 주소" /></View><View style={st.routeMap}><View style={st.mapWater} /><Text style={st.mapWaterText}>SEA</Text><Text style={st.mapBadge}>예시 동선 · 실제 지도 아님</Text><View style={st.mapRoad} />{foundPlaces.slice(0, 3).map((p, i) => <Pressable key={p.id} accessibilityRole="button" accessibilityLabel={`${p.name} 선택`} onPress={() => setSelectedPlaceId(p.id)} style={[st.mapPin, { top: 58 + i * 53, left: 24 + (i % 2) * 50 }]}><View style={[st.pinNumber, p.id === selectedPlace?.id && { backgroundColor: c.orange }]}><Text style={st.pinText}>{i + 1}</Text></View><Text style={st.mapPlaceText}>{p.name}</Text></Pressable>)}</View>
        {selectedPlace && <View style={[s.card, { marginTop: 14 }]}><Text style={st.tag}>{selectedPlace.category}</Text><Text style={[s.h2, { marginVertical: 9 }]}>{selectedPlace.name}</Text><Text style={s.body}>{selectedPlace.address}</Text><Text style={[s.body, { marginBottom: 16 }]}>{selectedPlace.note}</Text><Button label="이 장소를 일정에 추가" secondary onPress={() => open('schedule', { title: selectedPlace.name, place: selectedPlace.name, time: '14:00' })} /></View>}
        <Heading action="장소 추가" onPress={() => open('place')}>저장한 장소 {foundPlaces.length}</Heading>{foundPlaces.map(p => <Pressable accessibilityRole="button" accessibilityLabel={`${p.name} 상세`} key={p.id} onPress={() => setSelectedPlaceId(p.id)} style={st.placeRow}><View style={st.placeIcon}><Icon name="pin" color={c.green} /></View><View style={{ flex: 1 }}><Text style={st.eventTitle}>{p.name}</Text><Label>{p.category} · {p.address}</Label></View><Icon name="arrow" size={16} /></Pressable>)}{!foundPlaces.length && <Empty title="저장한 장소가 없어요" detail="검색어를 바꾸거나 새 장소를 추가해 보세요." />}
      </>}
      {tab === 'expenses' && <><View style={s.between}><View><Text style={st.pageTitle}>비용도 사이좋게</Text><Text style={s.body}>함께 쓴 만큼, 깔끔하게 나눠요.</Text></View><IconButton name="plus" label="지출 추가" onPress={() => open('expense')} /></View><View style={st.totalCard}><Text style={st.totalLabel}>우리 여행의 공동 지출</Text><Text style={st.totalAmount}>{won(total)}</Text><View style={st.totalDivider} /><View style={s.between}><Text style={st.totalLabel}>내 부담액 · 지우</Text><Text style={st.totalShare}>{won(accounting.balances['지우'].share)}</Text></View></View><View style={st.wrap}>{['지출 내역', '정산 결과'].map(label => <Chip key={label} label={label} selected={costView === label} onPress={() => setCostView(label)} />)}</View>
        {costView === '지출 내역' ? <><Heading>지출 {trip.expenses.length}건</Heading>{trip.expenses.map(e => <View key={e.id} style={st.expenseRow}><View style={st.placeIcon}><Icon name="wallet" color={c.green} size={20} /></View><View style={{ flex: 1 }}><Text style={st.eventTitle}>{e.title}</Text><Label>{e.payer} 결제 · {e.participants.length}명 분담</Label></View><Text style={st.money}>{won(e.amount)}</Text></View>)}{!trip.expenses.length && <Empty title="아직 기록한 지출이 없어요" detail="첫 지출을 추가하면 정산 금액이 계산돼요." />}<View style={{ marginTop: 20 }}><Button label="지출 기록하기" icon="plus" onPress={() => open('expense')} /></View></> : <><Heading>이렇게 나누면 돼요</Heading>{accounting.transfers.map((t, i) => <View key={i} style={[s.card, { marginBottom: 10 }]}><View style={s.between}><Text style={st.eventTitle}>{t.from} → {t.to}</Text><Text style={st.money}>{won(t.amount)}</Text></View></View>)}{!accounting.transfers.length && <Empty title="주고받을 금액이 없어요" detail="모두의 결제액과 부담액이 같아요." />}<Heading>멤버별 내역</Heading>{members.map(m => <View key={m} style={st.memberBalance}><Text style={st.eventTitle}>{m}{m === '지우' ? ' (나)' : ''}</Text><Label>결제 {won(accounting.balances[m].paid)} / 부담 {won(accounting.balances[m].share)}</Label></View>)}<Text style={st.footnote}>원 단위 나머지는 선택된 멤버 순서로 배분해요.{ '\n' }송금은 연결되지 않은 계산 데모예요.</Text></>}
      </>}
      {tab === 'chat' && <><Text style={st.pageTitle}>우리끼리 이야기</Text><Text style={s.body}>멤버 4명 · 여행 전체 대화</Text><Pressable accessibilityRole="button" onPress={() => open('notice', { notice: trip.notice })} style={st.notice}><Icon name="bell" size={18} /><Text numberOfLines={2} style={[st.noticeText, { flex: 1 }]}>{trip.notice}</Text></Pressable><Text style={st.chatDate}>여행 대화 · 예시 메시지</Text>{trip.messages.map(m => <View key={m.id} style={[st.messageRow, m.author === '지우' && { alignItems: 'flex-end' }]}>{m.author !== '지우' && <Text style={st.sender}>{m.author}</Text>}<View style={[st.bubble, m.author === '지우' && st.myBubble]}><Text style={[st.messageText, m.author === '지우' && st.onGreen]}>{m.text}</Text></View><Text style={st.messageTime}>{m.time}</Text></View>)}{!trip.messages.length && <Empty title="첫 인사를 남겨 주세요" detail="오늘은 어떤 여행을 하고 싶나요?" />}</>}
      <Text style={st.demoNote}>로컬 데모 · 새로고침하면 입력한 내용이 초기화돼요.</Text>
    </ScrollView>
    {tab === 'chat' && <View style={st.composer}><TextInput accessibilityLabel="메시지" value={message} onChangeText={setMessage} placeholder="여행 이야기를 나눠 보세요" placeholderTextColor={c.muted} style={st.messageInput} maxLength={1000} onSubmitEditing={send} returnKeyType="send" /><Pressable accessibilityRole="button" accessibilityLabel="메시지 보내기" onPress={send} disabled={!message.trim()} style={[st.send, !message.trim() && { opacity: 0.4 }]}><Icon name="send" color={c.white} /></Pressable></View>}
    </KeyboardAvoidingView>
    <View accessibilityRole="tablist" style={st.tabs}>{tabs.map(t => <Pressable key={t.key} accessibilityRole="tab" accessibilityLabel={t.label} accessibilityState={{ selected: tab === t.key }} onPress={() => go(t.key)} style={st.tab}><View style={[st.tabIcon, tab === t.key && st.tabActive]}><Icon name={t.icon} color={tab === t.key ? c.green : c.muted} size={23} /></View><Text style={[st.tabLabel, tab === t.key && { color: c.green, fontWeight: '700' }]}>{t.label}</Text></Pressable>)}</View>
    <Modal visible={sheet !== null} transparent animationType="slide" onRequestClose={() => setSheet(null)}><View style={st.scrim}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={st.modalShell}><SafeAreaView style={st.modal} edges={['top', 'bottom']}><View style={st.modalHeader}><Text style={s.h2}>{{ trips: '내 여행', newTrip: '새 여행 만들기', members: '함께하는 사람들', notice: '여행 공지', schedule: editId ? '일정 수정' : '일정 추가', expense: '지출 기록', place: '장소 저장', checklist: '여행 준비물' }[sheet ?? 'trips']}</Text><IconButton name="close" label="닫기" onPress={() => setSheet(null)} /></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={st.modalContent}>
      {sheet === 'trips' && <><Text style={s.body}>우리의 다음 여행은 어디일까요?</Text>{trips.map(t => <Pressable accessibilityRole="button" key={t.id} onPress={() => chooseTrip(t)} style={[s.card, { marginVertical: 12, backgroundColor: t.id === tripId ? c.pale : c.white }]}><Text style={s.h2}>{t.name}</Text><Label>{t.region} · {shortDate(t.dates[0])} — {shortDate(t.dates[t.dates.length - 1])} · 4명</Label></Pressable>)}<Button label="새 여행 만들기" icon="plus" onPress={() => open('newTrip', { start: '2026-09-19', end: '2026-09-20' })} /></>}
      {sheet === 'newTrip' && <><Field label="여행 이름" {...input('title')} placeholder="예: 부산에서 보내는 주말" maxLength={40} /><Field label="여행 지역" {...input('region')} placeholder="예: 부산" maxLength={20} /><Field label="시작일 (YYYY-MM-DD)" {...input('start')} /><Field label="종료일 (YYYY-MM-DD)" {...input('end')} /><Text style={s.body}>데모 멤버 지우·민수·서연·도윤과 함께 시작해요.</Text></>}
      {sheet === 'members' && <><Text style={s.body}>우리 여행의 멤버 {members.length}명</Text>{members.map((m, i) => <View key={m} style={st.placeRow}><View style={[st.avatar, { width: 42, height: 42, marginLeft: 0 }]}><Text style={st.avatarText}>{m[0]}</Text></View><Text style={st.eventTitle}>{m}</Text><Label>{i === 0 ? '나' : i === 1 ? '여행장' : '멤버'}</Label></View>)}<Heading>잠깐 따로, 다시 함께</Heading><View style={s.card}><Text style={st.eventTitle}>카페 파티 · 지우, 서연</Text><Text style={[s.body, { marginBottom: 16 }]}>커피 한 잔과 여유로운 오후</Text><Text style={st.eventTitle}>바다 파티 · 민수, 도윤</Text><Text style={s.body}>해변을 따라 걷는 시간</Text></View><Text style={st.footnote}>데모에서는 멤버·파티를 예시로 고정했어요.</Text></>}
      {sheet === 'notice' && <Field label="멤버들에게 전할 공지" multiline {...input('notice')} maxLength={1000} />}
      {sheet === 'schedule' && <><Label>{shortDate(trip.dates[day])} · {day + 1}일차에 추가</Label><View style={{ height: 16 }} /><Field label="일정 제목" {...input('title')} placeholder="무엇을 할까요?" maxLength={80} /><Field label="시간 (HH:MM)" {...input('time')} placeholder="14:00" keyboardType="numbers-and-punctuation" /><Field label="장소" {...input('place')} placeholder="장소 이름 또는 주소" maxLength={100} /><Label>함께할 파티</Label><View style={[st.wrap, { marginVertical: 12 }]}>{parties.map(p => <Chip key={p} label={p} selected={formParty === p} onPress={() => setFormParty(p)} />)}</View></>}
      {sheet === 'expense' && <><Field label="지출 항목" {...input('title')} placeholder="예: 함께 먹은 저녁" maxLength={80} /><Field label="금액 (원)" {...input('amount')} placeholder="48000" keyboardType="number-pad" /><Label>결제한 사람</Label><View style={[st.wrap, { marginVertical: 12 }]}>{members.map(m => <Chip key={m} label={m} selected={payer === m} onPress={() => setPayer(m)} />)}</View><Label>비용을 나눌 멤버 · 선택한 사람끼리 균등 분할</Label><View style={[st.wrap, { marginVertical: 12 }]}>{members.map(m => <Chip key={m} label={`${participants.includes(m) ? '✓ ' : ''}${m}`} selected={participants.includes(m)} onPress={() => setParticipants(list => list.includes(m) ? list.filter(x => x !== m) : [...list, m])} />)}</View><Text style={s.body}>{participants.length}명 선택 · 1원 단위 나머지는 멤버 순서로 배분돼요.</Text></>}
      {sheet === 'place' && <><Field label="장소 이름" {...input('title')} placeholder="어디에 가고 싶나요?" maxLength={80} /><Field label="분류" {...input('category')} placeholder="카페, 음식점, 숙소, 볼거리" maxLength={20} /><Field label="주소" {...input('address')} placeholder="장소의 주소" maxLength={120} /><Field label="메모" {...input('note')} multiline placeholder="이곳에서 하고 싶은 일" maxLength={300} /></>}
      {sheet === 'checklist' && <><Text style={s.body}>{completed} / {trip.checklist.length}개 준비 완료</Text><Checklist /><View style={{ marginTop: 20 }}><Field label="새 준비물" value={checkInput} onChangeText={setCheckInput} placeholder="빠뜨린 준비물이 있나요?" maxLength={80} onSubmitEditing={addCheck} /><Button label="준비물 추가" icon="plus" onPress={addCheck} /></View></>}
      {!!error && <Text accessibilityRole="alert" style={st.error}>{error}</Text>}
      {sheet && !['trips', 'members', 'checklist'].includes(sheet) && <View style={{ marginTop: 20, gap: 12 }}><Button label={sheet === 'newTrip' ? '여행 만들기' : '저장하기'} onPress={save} />{sheet === 'schedule' && editId && <Button label="이 일정 삭제" secondary onPress={() => { update(t => ({ ...t, schedules: t.schedules.filter(item => item.id !== editId) })); setSheet(null); }} />}</View>}
    </ScrollView></SafeAreaView></KeyboardAvoidingView></View></Modal>
  </SafeAreaView></View>;
}

const st = StyleSheet.create({
  outer: { flex: 1, backgroundColor: '#EAF0EB', alignItems: 'center' }, app: { width: '100%', maxWidth: 480, flex: 1, backgroundColor: c.paper },
  topbar: { paddingHorizontal: 24, paddingTop: 10, paddingBottom: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  brandMark: { width: 33, height: 33, borderRadius: 11, backgroundColor: c.green, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '-6deg' }] }, brand: { fontSize: 22, fontWeight: '800', color: c.ink, letterSpacing: -1 }, demo: { color: c.green, fontSize: 9, letterSpacing: 1.5, backgroundColor: c.pale, padding: 5, borderRadius: 5, fontWeight: '700' },
  tripbar: { paddingHorizontal: 24, paddingBottom: 17, borderBottomWidth: 1, borderBottomColor: c.line, flexDirection: 'row', alignItems: 'center', gap: 8 }, tripName: { fontSize: 16, fontWeight: '700', color: c.ink, marginBottom: 5 }, avatars: { flexDirection: 'row', alignItems: 'center', paddingLeft: 5, gap: 2 }, avatar: { width: 29, height: 29, backgroundColor: c.pale, borderRadius: 30, borderWidth: 2, borderColor: c.paper, marginLeft: -6, alignItems: 'center', justifyContent: 'center' }, avatarText: { fontSize: 11, fontWeight: '700', color: c.ink },
  content: { padding: 22, paddingBottom: 20 }, hero: { backgroundColor: '#DDEBDD', minHeight: 250, borderRadius: 24, overflow: 'hidden', position: 'relative' }, heroCopy: { padding: 23, zIndex: 1 }, eyebrow: { fontSize: 9, letterSpacing: 1.8, fontWeight: '700', color: c.green }, heroTitle: { fontSize: 29, lineHeight: 39, fontWeight: '800', color: c.ink, marginTop: 15, letterSpacing: -1.4 }, heroSubtitle: { fontSize: 12, color: '#486C58', marginTop: 9 }, heroButton: { marginTop: 22, flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', paddingVertical: 11, paddingHorizontal: 14, borderRadius: 13, gap: 10, backgroundColor: '#FFFFFFDD' }, heroButtonText: { fontSize: 12, fontWeight: '700', color: c.green }, sun: { position: 'absolute', top: 33, right: 27, width: 49, height: 49, borderRadius: 50, backgroundColor: '#F3C878' }, waveBack: { position: 'absolute', backgroundColor: '#91C3AE', width: 260, height: 130, borderRadius: 100, right: -108, bottom: 25, transform: [{ rotate: '-30deg' }] }, waveFront: { position: 'absolute', backgroundColor: '#4B957B', width: 230, height: 105, borderRadius: 80, right: -60, bottom: -43, transform: [{ rotate: '-18deg' }] }, heroStamp: { position: 'absolute', bottom: 13, right: 15, fontSize: 9, fontWeight: '600', letterSpacing: 1.1, color: c.white },
  notice: { marginTop: 18, padding: 14, backgroundColor: '#F2F3E9', borderRadius: 16, flexDirection: 'row', gap: 11, alignItems: 'center' }, noticeIcon: { width: 31, height: 34, alignItems: 'center', justifyContent: 'center' }, noticeLabel: { fontSize: 10, fontWeight: '600', color: c.green, marginBottom: 4 }, noticeText: { fontSize: 12, lineHeight: 20, color: c.ink },
  timelineRow: { flexDirection: 'row', minHeight: 112 }, timeColumn: { width: 60, position: 'relative', paddingTop: 5 }, time: { fontSize: 12, fontWeight: '700', color: c.green }, dot: { width: 7, height: 7, borderRadius: 7, position: 'absolute', top: 31, left: 15 }, stem: { width: 1, position: 'absolute', top: 43, bottom: 1, left: 18, backgroundColor: c.line }, event: { flex: 1, paddingBottom: 20, paddingTop: 2 }, eventTitle: { fontSize: 14, fontWeight: '700', color: c.ink, flexShrink: 1 }, tag: { fontSize: 10, lineHeight: 18, color: c.green, backgroundColor: c.pale, alignSelf: 'flex-start', borderRadius: 5, paddingHorizontal: 7, marginTop: 8, overflow: 'hidden' },
  progress: { height: 4, backgroundColor: c.pale, borderRadius: 4, marginBottom: 14, overflow: 'hidden' }, progressFill: { height: 4, backgroundColor: c.green, borderRadius: 4 }, checkRow: { minHeight: 49, flexDirection: 'row', alignItems: 'center', gap: 10 }, checkbox: { width: 20, height: 20, borderRadius: 6, borderWidth: 1.5, borderColor: '#C9D5CC', alignItems: 'center', justifyContent: 'center' }, checkText: { flex: 1, fontSize: 13, lineHeight: 20, color: c.ink }, checkedText: { textDecorationLine: 'line-through', color: c.muted }, checkMore: { borderTopWidth: 1, borderTopColor: c.line, marginTop: 10, paddingTop: 14, minHeight: 44, alignItems: 'center' }, costPreview: { padding: 20, borderRadius: 20, backgroundColor: c.pale, marginTop: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, costNumber: { fontSize: 23, fontWeight: '800', color: c.ink, marginTop: 5 },
  pageTitle: { fontSize: 25, letterSpacing: -1, fontWeight: '800', color: c.ink, marginBottom: 8 }, dateRow: { gap: 10, paddingVertical: 23 }, date: { width: 81, padding: 14, borderRadius: 17, backgroundColor: c.pale, alignItems: 'center', gap: 7 }, dateActive: { backgroundColor: c.green }, dayLabel: { fontSize: 10, fontWeight: '700', color: c.muted, letterSpacing: 1 }, dateLabel: { fontSize: 18, fontWeight: '700', color: c.ink }, onGreen: { color: c.white }, wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, footnote: { fontSize: 12, lineHeight: 20, color: c.muted, textAlign: 'center', marginTop: 20 },
  routeMap: { height: 260, backgroundColor: '#E9EEE0', borderRadius: 22, overflow: 'hidden', position: 'relative' }, mapWater: { position: 'absolute', width: '38%', top: -20, bottom: -20, right: -22, borderTopLeftRadius: 80, borderBottomLeftRadius: 130, backgroundColor: '#B3D5D4', transform: [{ rotate: '10deg' }] }, mapWaterText: { position: 'absolute', right: 18, top: 115, color: '#558E94', fontSize: 12, letterSpacing: 3 }, mapBadge: { position: 'absolute', top: 15, left: 15, color: c.muted, fontSize: 10, backgroundColor: '#FFFFFFCB', borderRadius: 8, padding: 7 }, mapRoad: { position: 'absolute', top: 80, left: 60, width: 36, height: 130, borderLeftWidth: 3, borderBottomWidth: 3, borderColor: '#A5B79E', borderStyle: 'dashed', transform: [{ rotate: '-15deg' }] }, mapPin: { position: 'absolute', flexDirection: 'row', alignItems: 'center', gap: 7, minHeight: 44 }, pinNumber: { backgroundColor: c.green, width: 29, height: 29, borderRadius: 30, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: c.white }, pinText: { color: c.white, fontSize: 12, fontWeight: '700' }, mapPlaceText: { fontSize: 11, color: c.ink, fontWeight: '600', backgroundColor: '#FFFFFFDE', padding: 5, borderRadius: 5, maxWidth: 138 }, placeRow: { paddingVertical: 14, flexDirection: 'row', gap: 12, alignItems: 'center', borderBottomWidth: 1, borderBottomColor: c.line }, placeIcon: { backgroundColor: c.pale, width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  totalCard: { padding: 24, backgroundColor: c.green, borderRadius: 23, marginVertical: 23 }, totalLabel: { color: '#D2E5D8', fontSize: 12 }, totalAmount: { color: c.white, fontSize: 34, fontWeight: '800', letterSpacing: -1, marginTop: 12 }, totalDivider: { height: 1, backgroundColor: '#FFFFFF30', marginVertical: 20 }, totalShare: { color: c.white, fontSize: 15, fontWeight: '700' }, expenseRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 18, borderBottomWidth: 1, borderBottomColor: c.line }, money: { fontSize: 14, fontWeight: '700', color: c.ink }, memberBalance: { paddingVertical: 14, gap: 8, borderBottomWidth: 1, borderBottomColor: c.line },
  chatDate: { fontSize: 10, textAlign: 'center', color: c.muted, marginVertical: 25 }, messageRow: { marginBottom: 19, alignItems: 'flex-start', gap: 5 }, sender: { fontSize: 11, color: c.muted, marginLeft: 5 }, bubble: { padding: 15, backgroundColor: c.pale, borderRadius: 18, borderTopLeftRadius: 4, maxWidth: '86%' }, myBubble: { backgroundColor: c.green, borderTopLeftRadius: 18, borderTopRightRadius: 4 }, messageText: { fontSize: 14, lineHeight: 23, color: c.ink }, messageTime: { fontSize: 9, color: c.muted, marginHorizontal: 5 }, composer: { paddingHorizontal: 20, paddingVertical: 12, flexDirection: 'row', gap: 10, borderTopWidth: 1, borderTopColor: c.line }, messageInput: { backgroundColor: c.pale, padding: 13, borderRadius: 16, flex: 1, minWidth: 0, fontSize: 14, color: c.ink }, send: { width: 46, height: 46, backgroundColor: c.green, alignItems: 'center', justifyContent: 'center', borderRadius: 16 },
  demoNote: { textAlign: 'center', fontSize: 10, color: c.muted, marginTop: 28, lineHeight: 17 }, tabs: { flexDirection: 'row', backgroundColor: c.paper, borderTopWidth: 1, borderTopColor: c.line, paddingTop: 10, paddingBottom: 9, paddingHorizontal: 9 }, tab: { flex: 1, alignItems: 'center', gap: 5, minHeight: 56 }, tabIcon: { width: 49, height: 32, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, tabActive: { backgroundColor: c.pale }, tabLabel: { fontSize: 10, color: c.muted },
  scrim: { flex: 1, justifyContent: 'flex-end', alignItems: 'center', backgroundColor: '#102A2466' }, modalShell: { width: '100%', maxWidth: 480, maxHeight: '94%' }, modal: { backgroundColor: c.paper, borderTopLeftRadius: 25, borderTopRightRadius: 25, overflow: 'hidden', flexShrink: 1 }, modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, borderBottomWidth: 1, borderBottomColor: c.line }, modalContent: { padding: 24, paddingBottom: 36 }, error: { color: c.red, fontSize: 13, lineHeight: 21, marginTop: 15 },
});
