import contextlib,io,struct,zlib,json,math
from pathlib import Path
with contextlib.redirect_stdout(io.StringIO()):
 import inspect_hwp as h
r=[(t,l,bytes.fromhex(d)) for t,l,d in json.loads(Path('tmp/pdfs/week1/records.json').read_text())]
content={
161:'그룹 여행 통합 관리 앱의 개발 방향과 핵심 기능을 정리하고, 14주 추진 일정 및 팀원별 역할을 수립한다. 프론트엔드·백엔드·DB 기술을 선정하여 기초 개발 환경을 마련한다.',
174:'여행 일정·장소·비용·준비물 정보가 여러 앱에 분산되는 불편을 해결하기 위해 그룹 여행에 필요한 기능을 하나의 앱에서 관리하는 방향을 정리하였다. 향후 AI 기반 맞춤형 여행 일정 추천으로 확장할 계획을 세웠다. 개발 일정은 기획 및 환경 구축, DB·API 설계와 UI 구성, 로그인·여행방, 일정·장소 등록, 동선 시각화, 비용 정산, 그룹 채팅, GPS 위치 공유, AI 챗봇, 통합 및 QA 순으로 구체화하였다. 팀장인 본인은 프론트엔드와 AI 설계를, 김시형은 백엔드 구축을, 윤호영은 프로젝트 매니저 역할을 맡기로 하였다. 프론트엔드는 Android와 iOS를 하나의 코드베이스로 개발할 수 있고 기존 개발 경험을 활용할 수 있는 React Native를 선정하였다. 백엔드는 REST API와 비즈니스 로직 구현에 적합한 Spring Boot, DB는 관계형 데이터 관리 및 Spring Boot 연동이 용이한 MySQL을 선정하고 기초 환경 구축 방향을 정리하였다.',
183:'팀원들과 개발 주제와 기능 범위, 역할 분담 및 주차별 일정을 논의하였다. 각 기술의 특성과 프로젝트 적합성을 비교하고, 선정 이유와 1주차 진행 내용을 발표 자료로 정리하였다.',
199:'앱의 개발 목적과 핵심 기능, 14주 추진 일정 및 팀원별 역할을 구체화하였다. React Native·Spring Boot·MySQL을 개발 기술로 선정하여 기초 개발 방향을 마련하였다. 기획 및 기술 선정 목표를 달성하였으며, 세부 DB·API 설계와 UI 뼈대 구현은 다음 주부터 진행한다.',
212:'10조 1주차 발표 자료 「여행 통합 관리 앱」: 주제 선택 배경, 프로젝트 일정, 팀원 소개, 1주차 프로젝트 현황 및 내주 계획.',
223:'DB·API 설계 및 UI 뼈대 구축을 진행한다. 프론트엔드 담당자로서 주요 화면 구성과 화면 간 이동 흐름을 설계하고 React Native 기반 UI 구조를 마련한다. 백엔드 담당자와 화면별 필요 데이터 및 API 연동 항목을 협의한다.'
}
# Replace only the six content paragraphs. Preserve table cells and all other material.
out=[]; i=0
while i<len(r):
 if i not in content: out.append(r[i]); i+=1; continue
 start=i; end=i+1
 while end<len(r) and r[end][1]>2: end+=1
 old=r[start:end]; header=bytearray(old[0][2]); text=content[start]+'\r'
 # Keep the column-definition control in the references cell.
 prefix='\x02汤捯\x00\x00\x00\x00\x02' if start==212 else ''
 text=prefix+text; data=text.encode('utf-16le')
 oldcount=struct.unpack_from('<I',header)[0]; struct.pack_into('<I',header,0,(oldcount&0x80000000)|len(data)//2)
 if start==223: struct.pack_into('<I',header,4,0)
 struct.pack_into('<H',header,12,1); struct.pack_into('<H',header,14,0)
 # Layout cache is regenerated by Hancom on opening.
 struct.pack_into('<H',header,16,0)
 out.extend([(66,2,bytes(header)),(67,3,data),(68,3,struct.pack('<II',0,10))])
 if start==212: out.extend(x for x in old if x[0]==71)
 i=end
raw=b''.join(struct.pack('<I',t|(l<<10)|(len(d)<<20))+d for t,l,d in out)
c=zlib.compressobj(9,zlib.DEFLATED,-15); body=c.compress(raw)+c.flush()
streams={e['off']:h.read(e) for e in h.entries if e['type']==2}
sec=next(e for e in h.entries if e['name']=='Section0');streams[sec['off']]=body
preview=next(e for e in h.entries if e['name']=='PrvText')
streams[preview['off']]=('\r\n'.join(['2026-2학기 세종창의학기제 주간학습보고서 (1주차)','10조 최정흠 / 22011683 / 2026.09.01.~2026.09.07']+[k+'\r\n'+content[n] for k,n in zip(['금주 학습목표','학습내용','학습방법','학습성과 및 목표달성도','참고자료 및 문헌','내주 계획'],content)])).encode('utf-16le')
# Rebuild the compound file, preserving the directory tree and original binary assets.
ss=h.ss; sectors=[]; fat=[]
def alloc(data):
 first=len(sectors); count=math.ceil(len(data)/ss)
 for n in range(count):
  sectors.append(data[n*ss:(n+1)*ss].ljust(ss,b'\0'));fat.append(first+n+1 if n<count-1 else 0xfffffffe)
 return first if count else 0xfffffffe
directory=bytearray(h.dirs);mini=bytearray();minifat=[]
for e in h.entries:
 if e['type']!=2:continue
 data=streams[e['off']]
 if len(data)<4096:
  first=len(minifat);count=math.ceil(len(data)/64)
  for j in range(count):
   mini.extend(data[j*64:(j+1)*64].ljust(64,b'\0'));minifat.append(first+j+1 if j<count-1 else 0xfffffffe)
  first=first if count else 0xfffffffe
 else:first=alloc(data)
 struct.pack_into('<I',directory,e['off']+116,first);struct.pack_into('<Q',directory,e['off']+120,len(data))
rootstart=alloc(mini);struct.pack_into('<I',directory,116,rootstart);struct.pack_into('<Q',directory,120,len(mini))
mfdata=struct.pack('<%dI'%len(minifat),*minifat);mfdata+=b'\xff'*((-len(mfdata))%ss);mfstart=alloc(mfdata)
dir_start=alloc(directory)
nf=math.ceil(len(sectors)/(ss//4-1))
while math.ceil((len(sectors)+nf)/(ss//4))>nf:nf+=1
fat_ids=list(range(len(sectors),len(sectors)+nf));fat.extend([0xfffffffd]*nf)
fat.extend([0xffffffff]*(nf*ss//4-len(fat)));fb=struct.pack('<%dI'%len(fat),*fat)
sectors.extend(fb[k*ss:(k+1)*ss] for k in range(nf))
header=bytearray(h.b[:ss]);struct.pack_into('<I',header,44,nf);struct.pack_into('<I',header,48,dir_start);struct.pack_into('<I',header,60,mfstart);struct.pack_into('<I',header,64,len(mfdata)//ss);struct.pack_into('<I',header,68,0xfffffffe);struct.pack_into('<I',header,72,0)
struct.pack_into('<109I',header,76,*(fat_ids+[0xffffffff]*(109-len(fat_ids))))
dest=Path('other_documents/2026-2학기__10_최정흠_주간학습보고서_1주차_작성본.hwp');dest.write_bytes(header+b''.join(sectors))
Path('other_documents/1주차_보고서_작성내용.txt').write_text('\n\n'.join(k+'\n'+content[n] for k,n in zip(['금주 학습목표','학습내용','학습방법','학습성과 및 목표달성도','참고자료 및 문헌','내주 계획'],content)),encoding='utf-8-sig')
print(dest, len(body))
