spring.application.name=travel-backend

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:validate}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false
auth.cookie-secure=${AUTH_COOKIE_SECURE:true}
