spring.application.name=travel-backend

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}

# Access Token 15분
jwt.access-token-expiration=900
# Refresh Token 14일
jwt.refresh-token-expiration=1209600
